name: quirky_quarters
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  camera: ^0.10.5+9
  google_ml_kit: ^0.16.3
  image_picker: ^0.8.5+3
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  google_fonts: ^6.2.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png