name: quirky_quarters
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 
  camera: 
  google_ml_kit:
  image_picker: ^0.8.5+3
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true