// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAffwgAC2PJlgBH4CX8qjeQktU6b2-O-Ns',
    appId: '1:961462713071:web:1eb7dbf2f021691d58f91a',
    messagingSenderId: '961462713071',
    projectId: 'quirky-quarters',
    authDomain: 'quirky-quarters.firebaseapp.com',
    storageBucket: 'quirky-quarters.appspot.com',
    measurementId: 'G-8VPGQHGS33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQl0rzVxig2SpPKvJdOsQzzxm8tkZ_a0',
    appId: '1:961462713071:android:750a71536213d44558f91a',
    messagingSenderId: '961462713071',
    projectId: 'quirky-quarters',
    storageBucket: 'quirky-quarters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_qjU50VcfwPQYVRxN4r1rLi3FuR4cyM',
    appId: '1:961462713071:ios:26f4842f3ac1542c58f91a',
    messagingSenderId: '961462713071',
    projectId: 'quirky-quarters',
    storageBucket: 'quirky-quarters.appspot.com',
    iosBundleId: 'com.example.QuirkyQuarters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_qjU50VcfwPQYVRxN4r1rLi3FuR4cyM',
    appId: '1:961462713071:ios:03cf728b6517571e58f91a',
    messagingSenderId: '961462713071',
    projectId: 'quirky-quarters',
    storageBucket: 'quirky-quarters.appspot.com',
    iosBundleId: 'com.example.namerApp.RunnerTests',
  );
}
